CREATE DATABASE moviesdb;

-- public.movie definition

-- Drop table

-- DROP TABLE public.movie;

CREATE TABLE public.movie (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	film varchar(100) NOT NULL,
	genre varchar(50) NULL,
	score int4 NULL,
	studio varchar(100) NULL,
	"year" int4 NULL,
	CONSTRAINT movie_pkey PRIMARY KEY (id)
);

INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('Zack and Miri Make a Porno','Romance',70,'The Weinstein Company',2008),
	 ('Youth in Revolt','Comedy',52,'The Weinstein Company',2010),
	 ('You Will Meet a Tall Dark Stranger','Comedy',35,'Independent',2010),
	 ('When in Rome','Comedy',44,'Disney',2010),
	 ('What Happens in Vegas','Comedy',72,'Fox',2008),
	 ('Water For Elephants','Drama',72,'20th Century Fox',2011),
	 ('WALL-E','Animation',89,'Disney',2008),
	 ('Waitress','Romance',67,'Independent',2007),
	 ('Waiting For Forever','Romance',53,'Independent',2011),
	 ('Valentine''s Day','Comedy',54,'Warner Bros.',2010);
INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('Tyler Perry''s Why Did I get Married','Romance',47,'Independent',2007),
	 ('Twilight: Breaking Dawn','Romance',68,'Independent',2011),
	 ('Twilight','Romance',82,'Summit',2008),
	 ('The Ugly Truth','Comedy',68,'Independent',2009),
	 ('The Twilight Saga: New Moon','Drama',78,'Summit',2009),
	 ('The Time Traveler''s Wife','Drama',65,'Paramount',2009),
	 ('The Proposal','Comedy',74,'Disney',2009),
	 ('The Invention of Lying','Comedy',47,'Warner Bros.',2009),
	 ('The Heartbreak Kid','Comedy',41,'Paramount',2007),
	 ('The Duchess','Drama',68,'Paramount',2008);
INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('The Curious Case of Benjamin Button','Fantasy',81,'Warner Bros.',2008),
	 ('The Back-up Plan','Comedy',47,'CBS',2010),
	 ('Tangled','Animation',88,'Disney',2010),
	 ('Something Borrowed','Romance',48,'Independent',2011),
	 ('She''s Out of My League','Comedy',60,'Paramount',2010),
	 ('Sex and the City Two','Comedy',49,'Warner Bros.',2010),
	 ('Sex and the City 2','Comedy',49,'Warner Bros.',2010),
	 ('Sex and the City','Comedy',81,'Warner Bros.',2008),
	 ('Remember Me','Drama',70,'Summit',2010),
	 ('Rachel Getting Married','Drama',61,'Independent',2008);
INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('Penelope','Comedy',74,'Summit',2008),
	 ('P.S. I Love You','Romance',82,'Independent',2007),
	 ('Over Her Dead Body','Comedy',47,'New Line',2008),
	 ('Our Family Wedding','Comedy',49,'Independent',2010),
	 ('One Day','Romance',54,'Independent',2011),
	 ('Not Easily Broken','Drama',66,'Independent',2009),
	 ('No Reservations','Comedy',64,'Warner Bros.',2007),
	 ('Nick and Norah''s Infinite Playlist','Comedy',67,'Sony',2008),
	 ('New Year''s Eve','Romance',48,'Warner Bros.',2011),
	 ('My Week with Marilyn','Drama',84,'The Weinstein Company',2011);
INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('Music and Lyrics','Romance',70,'Warner Bros.',2007),
	 ('Monte Carlo','Romance',50,'20th Century Fox',2011),
	 ('Miss Pettigrew Lives for a Day','Comedy',70,'Independent',2008),
	 ('Midnight in Paris','Romence',84,'Sony',2011),
	 ('Marley and Me','Comedy',77,'Fox',2008),
	 ('Mamma Mia!','Comedy',76,'Universal',2008),
	 ('Mamma Mia!','Comedy',76,'Universal',2008),
	 ('Made of Honor','Comdy',61,'Sony',2008),
	 ('Love Happens','Drama',40,'Universal',2009),
	 ('Love & Other Drugs','Comedy',55,'Fox',2010);
INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('Life as We Know It','Comedy',62,'Independent',2010),
	 ('License to Wed','Comedy',55,'Warner Bros.',2007),
	 ('Letters to Juliet','Comedy',62,'Summit',2010),
	 ('Leap Year','Comedy',49,'Universal',2010),
	 ('Knocked Up','Comedy',83,'Universal',2007),
	 ('Killers','Action',45,'Lionsgate',2010),
	 ('Just Wright','Comedy',58,'Fox',2010),
	 ('Jane Eyre','Romance',77,'Universal',2011),
	 ('It''s Complicated','Comedy',63,'Universal',2009),
	 ('I Love You Phillip Morris','Comedy',57,'Independent',2010);
INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('High School Musical 3: Senior Year','Comedy',76,'Disney',2008),
	 ('He''s Just Not That Into You','Comedy',60,'Warner Bros.',2009),
	 ('Good Luck Chuck','Comedy',61,'Lionsgate',2007),
	 ('Going the Distance','Comedy',56,'Warner Bros.',2010),
	 ('Gnomeo and Juliet','Animation',52,'Disney',2011),
	 ('Gnomeo and Juliet','Animation',52,'Disney',2011),
	 ('Ghosts of Girlfriends Past','Comedy',47,'Warner Bros.',2009),
	 ('Four Christmases','Comedy',52,'Warner Bros.',2008),
	 ('Fireproof','Drama',51,'Independent',2008),
	 ('Enchanted','Comedy',80,'Disney',2007);
INSERT INTO public.movie (film,genre,score,studio,"year") VALUES
	 ('Dear John','Drama',66,'Sony',2010),
	 ('Beginners','Comedy',80,'Independent',2011),
	 ('Across the Universe','romance',84,'Independent',2007),
	 ('A Serious Man','Drama',64,'Universal',2009),
	 ('A Dangerous Method','Drama',89,'Independent',2011),
	 ('27 Dresses','Comedy',71,'Fox',2008),
	 ('(500) Days of Summer','comedy',81,'Fox',2009),
	 ('Alien the 8th Passenger','Science Fiction',8,'20th Century Fox',1979);
